"""
Country Metadata: World Bank income groups, regions, and GDP per capita.
=========================================================================
Maps OECD.AI jurisdiction names → standardised metadata for analysis.

Sources:
  - World Bank income classifications (FY2025)
  - World Bank regions
  - IMF World Economic Outlook GDP per capita (PPP, 2024 est.)
"""

# World Bank Income Groups (FY2025)
# H = High income, UM = Upper middle, LM = Lower middle, L = Low
INCOME_GROUP = {
    'Algeria':          'LM',
    'Argentina':        'UM',
    'Armenia':          'UM',
    'Australia':        'H',
    'Austria':          'H',
    'Belgium':          'H',
    'Brazil':           'UM',
    'Bulgaria':         'UM',
    'Canada':           'H',
    'Chile':            'H',
    'China (People\'s Republic of)': 'UM',
    'Colombia':         'UM',
    'Costa Rica':       'UM',
    'Croatia':          'H',
    'Cyprus':           'H',
    'Czech Republic':   'H',
    'Denmark':          'H',
    'Egypt':            'LM',
    'Estonia':          'H',
    'Finland':          'H',
    'France':           'H',
    'Germany':          'H',
    'Greece':           'H',
    'Hungary':          'H',
    'Iceland':          'H',
    'India':            'LM',
    'Indonesia':        'LM',
    'Ireland':          'H',
    'Israel':           'H',
    'Italy':            'H',
    'Japan':            'H',
    'Kazakhstan':       'UM',
    'Kenya':            'LM',
    'Korea':            'H',
    'Latvia':           'H',
    'Lithuania':        'H',
    'Luxembourg':       'H',
    'Malaysia':         'UM',
    'Malta':            'H',
    'Mauritius':        'UM',
    'Mexico':           'UM',
    'Morocco':          'LM',
    'Netherlands':      'H',
    'New Zealand':      'H',
    'Nigeria':          'LM',
    'Norway':           'H',
    'Peru':             'UM',
    'Poland':           'H',
    'Portugal':         'H',
    'Romania':          'H',
    'Rwanda':           'L',
    'Saudi Arabia':     'H',
    'Serbia':           'UM',
    'Singapore':        'H',
    'Slovak Republic':  'H',
    'Slovenia':         'H',
    'South Africa':     'UM',
    'Spain':            'H',
    'Sweden':           'H',
    'Switzerland':      'H',
    'Thailand':         'UM',
    'Tunisia':          'LM',
    'Türkiye':          'UM',
    'Uganda':           'L',
    'Ukraine':          'LM',
    'United Arab Emirates': 'H',
    'United Kingdom':   'H',
    'United States':    'H',
    'Uruguay':          'H',
    'Uzbekistan':       'LM',
    'Viet Nam':         'LM',
    'Zambia':           'LM',
}

INCOME_LABELS = {
    'H':  'High income',
    'UM': 'Upper middle income',
    'LM': 'Lower middle income',
    'L':  'Low income',
}

# World Bank regions
REGION = {
    'Algeria':          'MENA',
    'Argentina':        'LAC',
    'Armenia':          'ECA',
    'Australia':        'EAP',
    'Austria':          'ECA',
    'Belgium':          'ECA',
    'Brazil':           'LAC',
    'Bulgaria':         'ECA',
    'Canada':           'NAM',
    'Chile':            'LAC',
    'China (People\'s Republic of)': 'EAP',
    'Colombia':         'LAC',
    'Costa Rica':       'LAC',
    'Croatia':          'ECA',
    'Cyprus':           'ECA',
    'Czech Republic':   'ECA',
    'Denmark':          'ECA',
    'Egypt':            'MENA',
    'Estonia':          'ECA',
    'Finland':          'ECA',
    'France':           'ECA',
    'Germany':          'ECA',
    'Greece':           'ECA',
    'Hungary':          'ECA',
    'Iceland':          'ECA',
    'India':            'SA',
    'Indonesia':        'EAP',
    'Ireland':          'ECA',
    'Israel':           'MENA',
    'Italy':            'ECA',
    'Japan':            'EAP',
    'Kazakhstan':       'ECA',
    'Kenya':            'SSA',
    'Korea':            'EAP',
    'Latvia':           'ECA',
    'Lithuania':        'ECA',
    'Luxembourg':       'ECA',
    'Malaysia':         'EAP',
    'Malta':            'ECA',
    'Mauritius':        'SSA',
    'Mexico':           'LAC',
    'Morocco':          'MENA',
    'Netherlands':      'ECA',
    'New Zealand':      'EAP',
    'Nigeria':          'SSA',
    'Norway':           'ECA',
    'Peru':             'LAC',
    'Poland':           'ECA',
    'Portugal':         'ECA',
    'Romania':          'ECA',
    'Rwanda':           'SSA',
    'Saudi Arabia':     'MENA',
    'Serbia':           'ECA',
    'Singapore':        'EAP',
    'Slovak Republic':  'ECA',
    'Slovenia':         'ECA',
    'South Africa':     'SSA',
    'Spain':            'ECA',
    'Sweden':           'ECA',
    'Switzerland':      'ECA',
    'Thailand':         'EAP',
    'Tunisia':          'MENA',
    'Türkiye':          'ECA',
    'Uganda':           'SSA',
    'Ukraine':          'ECA',
    'United Arab Emirates': 'MENA',
    'United Kingdom':   'ECA',
    'United States':    'NAM',
    'Uruguay':          'LAC',
    'Uzbekistan':       'ECA',
    'Viet Nam':         'EAP',
    'Zambia':           'SSA',
}

REGION_LABELS = {
    'EAP':  'East Asia & Pacific',
    'ECA':  'Europe & Central Asia',
    'LAC':  'Latin America & Caribbean',
    'MENA': 'Middle East & North Africa',
    'NAM':  'North America',
    'SA':   'South Asia',
    'SSA':  'Sub-Saharan Africa',
}

# GDP per capita, PPP (current int'l $, 2024 est., IMF WEO)
GDP_PER_CAPITA = {
    'Algeria':          13_500,
    'Argentina':        28_800,
    'Armenia':          20_100,
    'Australia':        65_400,
    'Austria':          72_000,
    'Belgium':          68_500,
    'Brazil':           20_800,
    'Bulgaria':         35_600,
    'Canada':           60_200,
    'Chile':            33_300,
    'China (People\'s Republic of)': 25_000,
    'Colombia':         19_700,
    'Costa Rica':       25_600,
    'Croatia':          42_500,
    'Cyprus':           52_800,
    'Czech Republic':   54_200,
    'Denmark':          77_600,
    'Egypt':            16_000,
    'Estonia':          51_500,
    'Finland':          62_200,
    'France':           63_000,
    'Germany':          68_200,
    'Greece':           42_700,
    'Hungary':          44_600,
    'Iceland':          75_200,
    'India':            10_100,
    'Indonesia':        16_600,
    'Ireland':          118_000,
    'Israel':           58_000,
    'Italy':            57_200,
    'Japan':            52_100,
    'Kazakhstan':       35_600,
    'Kenya':            6_400,
    'Korea':            56_700,
    'Latvia':           43_400,
    'Lithuania':        51_000,
    'Luxembourg':       141_000,
    'Malaysia':         38_500,
    'Malta':            61_000,
    'Mauritius':        30_800,
    'Mexico':           24_500,
    'Morocco':          10_500,
    'Netherlands':      74_000,
    'New Zealand':      52_200,
    'Nigeria':          6_100,
    'Norway':           87_900,
    'Peru':             16_900,
    'Poland':           47_200,
    'Portugal':         46_500,
    'Romania':          43_800,
    'Rwanda':           2_900,
    'Saudi Arabia':     65_600,
    'Serbia':           26_900,
    'Singapore':        133_700,
    'Slovak Republic':  43_100,
    'Slovenia':         55_600,
    'South Africa':     17_000,
    'Spain':            55_000,
    'Sweden':           72_500,
    'Switzerland':      91_900,
    'Thailand':         21_800,
    'Tunisia':          13_500,
    'Türkiye':          41_900,
    'Uganda':           2_900,
    'Ukraine':          16_400,
    'United Arab Emirates': 88_200,
    'United Kingdom':   62_400,
    'United States':    85_300,
    'Uruguay':          29_200,
    'Uzbekistan':       11_000,
    'Viet Nam':         15_500,
    'Zambia':           4_000,
}

# International / multi-country entities (excluded from country-level analysis)
INTERNATIONAL = {
    'European Union', 'OECD/GPAI', 'G7', 'African Union',
    'The United Nations Educational, Scientific and Cultural Organization',
    'United Nations', 'Inter-American Development Bank',
    'Association of Southeast Asian Nations', '',
}

# Convenience: binary high-income vs developing
def is_developing(jurisdiction: str) -> bool | None:
    """Returns True if lower-middle or low income, False if high/upper-middle, None if unknown."""
    ig = INCOME_GROUP.get(jurisdiction)
    if ig in ('LM', 'L'):
        return True
    elif ig in ('H', 'UM'):
        return False
    return None

def get_income_binary(jurisdiction: str) -> str | None:
    """Returns 'High income' or 'Developing' or None."""
    ig = INCOME_GROUP.get(jurisdiction)
    if ig == 'H':
        return 'High income'
    elif ig in ('UM', 'LM', 'L'):
        return 'Developing'
    return None

def get_metadata(jurisdiction: str) -> dict:
    """Get all metadata for a jurisdiction."""
    return {
        'income_group': INCOME_GROUP.get(jurisdiction),
        'income_label': INCOME_LABELS.get(INCOME_GROUP.get(jurisdiction, ''), 'Unknown'),
        'income_binary': get_income_binary(jurisdiction),
        'region': REGION.get(jurisdiction),
        'region_label': REGION_LABELS.get(REGION.get(jurisdiction, ''), 'Unknown'),
        'gdp_per_capita': GDP_PER_CAPITA.get(jurisdiction),
        'is_international': jurisdiction in INTERNATIONAL,
    }
