<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Capacity Dynamics – Global Observatory of AI Governance Capacity</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-ad92c8f6789d64c8f40a91dd2b038e8c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Global Observatory of AI Governance Capacity</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../book1_capacity/_book/index.html"> 
<span class="menu-text">Book 1 — Capacity</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../book2_ethics/_book/index.html"> 
<span class="menu-text">Book 2 — Ethics</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../book3_unesco/_book/index.html"> 
<span class="menu-text">Book 3 — UNESCO</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../book4_methods/_book/index.html"> 
<span class="menu-text">Book 4 — Methods</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/lsempe77/ai-governance-capacity"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#sec-cap-dynamics" id="toc-sec-cap-dynamics" class="nav-link active" data-scroll-target="#sec-cap-dynamics">Temporal Trends, Diffusion, and the Efficiency Frontier</a>
  <ul class="collapse">
  <li><a href="#sec-cap-temporal" id="toc-sec-cap-temporal" class="nav-link" data-scroll-target="#sec-cap-temporal">Temporal Trends</a></li>
  <li><a href="#sec-cap-diffusion" id="toc-sec-cap-diffusion" class="nav-link" data-scroll-target="#sec-cap-diffusion">Diffusion and the Efficiency Frontier</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Capacity Dynamics</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="sec-cap-dynamics" class="level2">
<h2 class="anchored" data-anchor-id="sec-cap-dynamics">Temporal Trends, Diffusion, and the Efficiency Frontier</h2>
<p>The preceding sections established the cross-sectional landscape: low average capacity, weak GDP effects, and inequality concentrated within income groups. This section introduces a temporal dimension, asking whether these patterns are stable, converging, or diverging over the 2017–2025 period. It then examines policy diffusion mechanisms—how governance approaches spread across jurisdictions—and identifies countries that achieve governance capacity exceeding expectations given their economic development level.</p>
<section id="sec-cap-temporal" class="level3">
<h3 class="anchored" data-anchor-id="sec-cap-temporal">Temporal Trends</h3>
<div id="fig-cap-temporal-dims" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cap-temporal-dims-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../data/analysis/paper1_capacity/fig_temporal_dimensions.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cap-temporal-dims-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Capacity dimension scores over time (2017–2025). Most dimensions show modest upward trends.
</figcaption>
</figure>
</div>
<div id="fig-cap-temporal-income" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cap-temporal-income-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../data/analysis/paper1_capacity/fig_temporal_income.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cap-temporal-income-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Capacity trends by income group over time. The gap between HI and developing countries remains stable.
</figcaption>
</figure>
</div>
<p>Individual dimensions trend modestly upward from 2017 to 2025, but the income-group gap stays flat: parallel lines, no convergence, no divergence:</p>
<div id="tbl-cap-convergence" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cap-convergence-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Convergence test for capacity scores
</figcaption>
<div aria-describedby="tbl-cap-convergence-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Metric</th>
<th style="text-align: left;">Capacity</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Income × Year interaction</td>
<td style="text-align: left;"><span class="math inline">\(\beta = +0.0003\)</span>, <span class="math inline">\(p = .98\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">HI temporal slope</td>
<td style="text-align: left;">−0.0001/yr (n.s.)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Developing temporal slope</td>
<td style="text-align: left;">+0.010/yr (n.s.)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gap trend</td>
<td style="text-align: left;">Stable</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>No convergence is detected.</strong> The interaction coefficient (β = +0.0003, p = .98) proves statistically indistinguishable from zero. High-income countries remain flat (−0.0001/yr, n.s.); developing countries show modest improvement at +0.010/yr (n.s.), insufficient to narrow existing gaps.</p>
<p>This pattern contrasts with ethics scores (see the ethics dynamics analysis), where significant convergence occurs through high-income countries <em>declining</em>. Capacity resists this pattern. The likely explanation: ethical principles can be adopted through citation of international frameworks, whereas building implementation infrastructure (budgets, staff, enforcement mechanisms) requires institutional development that policy learning alone cannot substitute. An alternative interpretation: if text quality improves over time (newer policies better documented), apparent stability could mask underlying changes. The robustness checks in <strong>?@sec-robustness</strong> address this possibility.</p>
<p><a href="#fig-cap-convergence" class="quarto-xref">Figure&nbsp;3</a> and <a href="#fig-cap-dim-convergence" class="quarto-xref">Figure&nbsp;4</a> present the detailed convergence analysis across dimensions and income groups, confirming the pattern of temporal stability.</p>
<div id="fig-cap-convergence" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cap-convergence-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../data/analysis/paper1_capacity/robustness/fig_convergence.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cap-convergence-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Detailed convergence analysis showing income-group trends and gap evolution for capacity dimensions.
</figcaption>
</figure>
</div>
<div id="fig-cap-dim-convergence" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cap-dim-convergence-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../data/analysis/paper1_capacity/robustness/fig_dimension_convergence.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cap-dim-convergence-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Dimension-level convergence patterns. No dimension shows statistically significant convergence.
</figcaption>
</figure>
</div>
</section>
<section id="sec-cap-diffusion" class="level3">
<h3 class="anchored" data-anchor-id="sec-cap-diffusion">Diffusion and the Efficiency Frontier</h3>
<p>The mechanisms of policy spread warrant examination. The comparative policy literature proposes two models. <strong>Vertical diffusion</strong> (Bradford’s <span class="citation" data-cites="bradford2020">[-@bradford2020]</span> “Brussels Effect”): innovations cascade from wealthy jurisdictions to developing countries through aid, technical assistance, and emulation. <strong>Horizontal diffusion</strong>: countries learn from peers facing similar constraints. The distinction carries policy implications: vertical diffusion suggests that strengthening high-income frameworks will eventually benefit developing countries; horizontal diffusion implies South-South cooperation proves more consequential.</p>
<p>This analysis tracks when each country first adopted AI governance policies and classifies diffusion direction.</p>
<div id="fig-cap-diffusion" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cap-diffusion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../data/analysis/paper1_capacity/frontier/fig_diffusion_curves.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cap-diffusion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Cumulative adoption curves by income group and region. HI countries adopted ~1.3 years earlier, but diffusion is overwhelmingly horizontal.
</figcaption>
</figure>
</div>
<div id="fig-cap-first-movers" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cap-first-movers-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../data/analysis/paper1_capacity/frontier/fig_first_movers.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cap-first-movers-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: First movers in AI governance capacity, plotted by adoption year and income group.
</figcaption>
</figure>
</div>
<div id="fig-cap-diffusion-heatmap" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cap-diffusion-heatmap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../data/analysis/paper1_capacity/frontier/fig_diffusion_heatmap.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cap-diffusion-heatmap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Regional diffusion heatmap showing the spread of AI governance policies across regions and years.
</figcaption>
</figure>
</div>
<p>The adoption curves show high-income countries reaching critical mass slightly earlier, but both groups surge in 2018–2020 in parallel, not sequential patterns:</p>
<div id="tbl-cap-diffusion" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cap-diffusion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Policy diffusion patterns for capacity
</figcaption>
<div aria-describedby="tbl-cap-diffusion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Metric</th>
<th style="text-align: left;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">HI median first adoption</td>
<td style="text-align: left;">2018</td>
</tr>
<tr class="even">
<td style="text-align: left;">Developing median first adoption</td>
<td style="text-align: left;">2019</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Adoption lag (HI earlier by)</td>
<td style="text-align: left;"><strong>1.3 years</strong> (<span class="math inline">\(p = .030\)</span>)</td>
</tr>
<tr class="even">
<td style="text-align: left;">HI adoption by 2025</td>
<td style="text-align: left;">98%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Developing adoption by 2025</td>
<td style="text-align: left;">86%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Diffusion direction</td>
<td style="text-align: left;"><strong>98% horizontal</strong></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>First, <strong>high-income countries adopt about 1.3 years earlier</strong> (median 2018 vs.&nbsp;2019, p = .030), statistically significant but substantively modest. By 2025, 98% of high-income and 86% of developing countries have adopted at least one AI governance policy. The gap is about timing, not whether countries adopt at all.</p>
<p>Second, and more important: <strong>98% of diffusion is horizontal.</strong> Countries learn from peers at similar income levels, not from wealthy-country frameworks cascading downward. This challenges the Brussels Effect hypothesis as applied to AI governance. I find minimal evidence of developing countries copying GDPR-inspired data protection or EU AI Act risk-based approaches. Instead, they build policies around their own institutional priorities and regulatory traditions.</p>
<p>Why? Wealthy-country models assume infrastructure that developing countries lack: data protection authorities, judicial capacity for algorithmic accountability, technical audit expertise. Direct transplantation is infeasible. Countries look to peers who adapted governance to similar resource constraints, or they resist perceived regulatory imperialism by developing indigenous approaches.</p>
<p>The mechanisms of horizontal diffusion are visible in the data. <strong>Regional bodies</strong> serve as transmission channels: the African Union’s Continental AI Strategy provided a shared template that Kenya, Rwanda, and South Africa adapted to national contexts; the Red Iberoamericana de Inteligencia Artificial connected Latin American policymakers drafting national strategies simultaneously; and ASEAN’s governance framework circulated among Southeast Asian countries with varying levels of AI maturity. <strong>Bilateral technical assistance</strong> between peers—Brazil advising Colombia, Singapore supporting ASEAN neighbours—transfers governance knowledge without the power asymmetry of North-South aid. <strong>International conferences and working groups</strong> (the Global Partnership on AI, the AI for Good summits, OECD committee meetings) create spaces where officials from similar-income countries compare approaches, often discovering that peers have solved problems they are facing. <strong>Policy entrepreneur networks</strong>—individuals who have drafted governance frameworks in one country and then advise neighbouring jurisdictions—facilitate direct knowledge transfer within income tiers.</p>
<p>The regions with the largest adoption lag, <strong>Sub-Saharan Africa and MENA</strong> (14–29% adoption by 2019 versus 100% in North America), lack these dense policy networks. They have fewer regional coordination mechanisms, fewer shared-language policy communities, and fewer international conference participants. Yet even these late adopters diffuse horizontally when they do adopt, suggesting that the constraint is network density rather than any inherent barrier to governance innovation.</p>
<p><strong>Governance efficiency frontier.</strong> GDP explains little, and diffusion is horizontal. But which specific countries punch above their weight? I use Free Disposable Hull (FDH) analysis to construct an efficiency frontier, connecting countries that achieve higher governance scores than any other country at similar or lower GDP.</p>
<div id="fig-cap-frontier" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cap-frontier-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../data/analysis/paper1_capacity/frontier/fig_efficiency_frontier.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cap-frontier-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: Efficiency frontier for capacity scores. Countries above the line outperform their GDP-predicted governance level; those below underperform.
</figcaption>
</figure>
</div>
<div id="fig-cap-residual" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cap-residual-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../data/analysis/paper1_capacity/frontier/fig_residual_ranking.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cap-residual-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: Residual ranking: countries sorted by their distance from GDP-predicted capacity. Brazil, Kenya, and Rwanda are the top overperformers.
</figcaption>
</figure>
</div>
<div id="fig-cap-overunder" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cap-overunder-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../data/analysis/paper1_capacity/frontier/fig_overunder_profile.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cap-overunder-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10: Profile comparison of over- and under-performers.
</figcaption>
</figure>
</div>
<p>Countries above the regression line in <a href="#fig-cap-frontier" class="quarto-xref">Figure&nbsp;8</a> outperform GDP predictions; those below underperform. <a href="#fig-cap-residual" class="quarto-xref">Figure&nbsp;9</a> ranks them by residual distance:</p>
<div id="tbl-cap-frontier" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cap-frontier-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Efficiency frontier results for capacity
</figcaption>
<div aria-describedby="tbl-cap-frontier-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Metric</th>
<th style="text-align: left;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">OLS <span class="math inline">\(R^2\)</span> (score ~ GDP)</td>
<td style="text-align: left;"><strong>0.035</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">Top overperformer</td>
<td style="text-align: left;">🇧🇷 Brazil (+0.69)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Top underperformer</td>
<td style="text-align: left;">🇰🇿 Kazakhstan (−0.75)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Frontier countries (FDH)</td>
<td style="text-align: left;">Uganda → Rwanda → Kenya → Brazil</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Most efficient (score/$10k GDP)</td>
<td style="text-align: left;">Rwanda (3.10), Kenya (1.91)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mean distance to frontier</td>
<td style="text-align: left;">0.588</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>GDP explains 3.5% of country-level capacity variation</strong> (R² = 0.035). The scatterplot disperses widely around the regression line. Knowing a country’s GDP tells you almost nothing about its governance capacity.</p>
<p>The frontier is anchored by African countries. <strong>Rwanda</strong> achieves 3.10 capacity points per $10K of GDP, nearly double Kenya’s 1.91 and far exceeding any high-income country’s efficiency ratio. Rwanda’s performance reflects deliberate institutional choices: a dedicated Centre for the Fourth Industrial Revolution (C4IR Kigali) that coordinates AI governance across ministries, data protection legislation with a functioning regulator, and national AI strategy documents that specify implementation timelines, responsible agencies, and budget allocations—precisely the capacity dimensions (C2, C3, C5) where most countries score weakest. <strong>Kenya</strong> established a Blockchain and AI Taskforce that produced binding recommendations, created a Data Protection Commissioner with enforcement powers, and embedded AI governance within its existing regulatory infrastructure rather than building parallel institutions. <strong>Uganda</strong> adopted binding data protection and AI governance legislation with enforcement mechanisms rivalling countries 10–20 times wealthier, leveraging its existing telecommunications regulator as an institutional anchor.</p>
<p><strong>Brazil</strong> is the top overall overperformer (+0.69 residual). Its success stems from layered institutional investment: the Brazilian AI Strategy (EBIA) designated MCTI as lead agency with cross-ministry coordination mechanisms (C5), the Marco Legal da IA established algorithmic accountability requirements with enforcement provisions (C4), and extensive multi-stakeholder consultation processes generated broad political buy-in that sustained implementation across government transitions. Brazil’s approach demonstrates that political commitment and institutional coordination, not fiscal abundance, drive governance capacity.</p>
<p>On the other side, <strong>Kazakhstan</strong> (−0.75 residual) and <strong>South Korea</strong> score well below GDP predictions. Both countries have the fiscal resources to build governance infrastructure but have not translated economic capacity into institutional commitment: policies remain declaratory (high on objectives, low on resources and accountability), coordination mechanisms are absent or fragmented, and monitoring provisions lack enforcement teeth. Wealth without political prioritisation and institutional coordination produces weak governance.</p>
<p>The mean distance to frontier (0.588) indicates most countries operate well below the efficiency boundary. There is room for improvement without additional resources, by learning from frontier peers at similar income levels.</p>
<p>This section points to three patterns:</p>
<ol type="1">
<li><p><strong>Temporal stability.</strong> The capacity gap is neither widening nor narrowing (2017–2025). Unlike ethics scores, which converge because high-income countries decline, capacity resists automatic improvement. Building implementation infrastructure requires targeted intervention, not diffusion alone.</p></li>
<li><p><strong>Horizontal diffusion.</strong> 98% of policy adoption occurs through within-group learning. Countries look to peers facing similar constraints, not to wealthy-country “best practice” models. Capacity-building should prioritize South-South cooperation over North-South transfer.</p></li>
<li><p><strong>GDP is not destiny.</strong> National wealth explains 3.5% of country-level capacity variation. Rwanda (3.10 per $10K GDP), Kenya, Uganda, and Brazil far exceed GDP predictions through strategic choices and institutional coordination. Kazakhstan and South Korea show that wealth without prioritization produces weak governance.</p></li>
</ol>
<p>The implications are clear: rather than waiting for economic development or transplanting wealthy-country models, effective capacity-building should support peer learning networks within income groups and study what enables frontier countries to outperform their resource constraints.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>